apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myapp-dev

resources:
  - namespace.yaml
  - ../../base

images:
  - name: ghcr.io/shin-sanghyeop/myapp
    newTag: 3d66b999d7e2c332a5bee34597d538fe605b104c