apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myapp-dev

resources:
  - namespace.yaml
  - ../../base

images:
  - name: IMAGE_PLACEHOLDER
    newName: ghcr.io/ORG_OR_USER/myapp
    newTag: latest